version: "3.9"
services:
  go:
    container_name: monorepo_go_api
    build:
      context: .
      target: dev
    volumes:
      - .:/go/src/app:rw,delegated
    networks:
      - monorepo_network
    ports:
      - "8080:8080"
      - "2345:2345"

networks:
  monorepo_network:
    name: monorepo_network
